<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Datacore — Book better stays</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600&family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500&family=Manrope:wght@500;600&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="font-inter overflow-x-hidden bg-[#2b2344] text-white">
    <main x-data="{ menuOpen: false }" class="relative isolate min-h-screen overflow-hidden">
        <video class="absolute inset-0 -z-10 h-full w-full object-cover" autoplay loop muted playsinline preload="metadata" aria-hidden="true"><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260210_031346_d87182fb-b0af-4273-84d1-c6fd17d6bf0f.mp4" type="video/mp4"></video>
        <nav class="relative z-20 flex items-center justify-between px-6 py-4 md:px-10 xl:px-[120px]" aria-label="Primary navigation">
            <a href="{{ route('home') }}" class="inline-flex h-11 items-center gap-2.5 rounded-lg px-1 focus:outline-none focus-visible:ring-4 focus-visible:ring-white/60" aria-label="Datacore home"><svg class="h-7 w-7" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M3 14 14 3l11 11-11 11L3 14Z" fill="white"/><path d="m10 14 4-4 4 4-4 4-4-4Z" fill="#7b39fc"/></svg><span class="font-manrope text-[15px] font-semibold tracking-[-0.03em]">datacore</span></a>
            <div class="ml-10 hidden items-center gap-8 lg:flex xl:mr-auto xl:ml-16"><a href="{{ route('home') }}" class="font-manrope text-sm font-medium text-white transition-opacity hover:opacity-80">Home</a><a href="#services" class="inline-flex items-center gap-1 font-manrope text-sm font-medium text-white transition-opacity hover:opacity-80">Services <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke-linecap="round" stroke-linejoin="round"/></svg></a><a href="#reviews" class="font-manrope text-sm font-medium text-white transition-opacity hover:opacity-80">Reviews</a><a href="#contact" class="font-manrope text-sm font-medium text-white transition-opacity hover:opacity-80">Contact us</a></div>
            <div class="hidden items-center gap-3 lg:flex"><a href="{{ route('login') }}" class="inline-flex min-h-10 items-center justify-center rounded-lg border border-[#d4d4d4] bg-white px-4 font-manrope text-sm font-semibold text-[#171717] transition-transform hover:-translate-y-0.5 focus:outline-none focus-visible:ring-4 focus-visible:ring-white/60">Sign In</a><a href="{{ route('register') }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-[#7b39fc] px-4 font-manrope text-sm font-semibold text-[#fafafa] shadow-[0_8px_20px_rgba(123,57,252,.35)] transition hover:-translate-y-0.5 hover:bg-[#8a50ff] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#b99aff]">Get Started</a></div>
            <button type="button" class="inline-flex h-11 w-11 items-center justify-center rounded-lg text-white transition hover:bg-white/10 focus:outline-none focus-visible:ring-4 focus-visible:ring-white/60 lg:hidden" x-on:click="menuOpen = true" aria-label="Open menu" aria-controls="mobile-menu" x-bind:aria-expanded="menuOpen.toString()"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" stroke-linecap="round"/></svg></button>
        </nav>
        <div id="mobile-menu" x-cloak x-show="menuOpen" x-transition.opacity class="fixed inset-0 z-50 flex min-h-dvh flex-col bg-black p-6" role="dialog" aria-modal="true" aria-label="Navigation menu"><div class="flex items-center justify-between"><span class="font-manrope text-lg font-semibold">datacore</span><button type="button" class="inline-flex h-11 w-11 items-center justify-center rounded-lg text-white hover:bg-white/10 focus:outline-none focus-visible:ring-4 focus-visible:ring-white/60" x-on:click="menuOpen = false" aria-label="Close menu"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18" stroke-linecap="round"/></svg></button></div><div class="mt-auto flex flex-col gap-6 pb-10 font-manrope text-3xl font-semibold"><a href="{{ route('home') }}" x-on:click="menuOpen = false">Home</a><a href="#services" x-on:click="menuOpen = false">Services</a><a href="#reviews" x-on:click="menuOpen = false">Reviews</a><a href="#contact" x-on:click="menuOpen = false">Contact us</a></div><div class="grid grid-cols-2 gap-3"><a href="{{ route('login') }}" class="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/25 font-manrope text-sm font-semibold">Sign In</a><a href="{{ route('register') }}" class="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#7b39fc] font-manrope text-sm font-semibold">Get Started</a></div></div>
        <section class="relative z-10 mx-auto flex min-h-[calc(100svh-76px)] max-w-6xl flex-col items-center justify-center px-6 pb-20 pt-20 text-center sm:pt-24" aria-labelledby="hero-title">
            <div class="datacore-enter datacore-enter--one inline-flex h-[38px] items-center gap-2 rounded-[10px] border border-[rgba(164,132,215,.5)] bg-[rgba(85,80,110,.4)] px-2.5 text-sm text-white shadow-[0_8px_30px_rgba(0,0,0,.12)] backdrop-blur-md"><span class="rounded-md bg-[#7b39fc] px-2 py-1 font-cabin text-xs font-medium">New</span><span class="font-cabin font-medium">Say Hello to Datacore v3.2</span></div>
            <h1 id="hero-title" class="datacore-enter datacore-enter--two mt-6 max-w-5xl font-instrument text-5xl leading-[1.02] tracking-[-0.045em] text-white drop-shadow-[0_3px_18px_rgba(0,0,0,.34)] sm:text-6xl md:text-7xl xl:text-[96px]">Book your perfect stay instantly <span class="mx-[.06em] italic">and</span> hassle-free</h1>
            <p class="datacore-enter datacore-enter--three mt-6 max-w-[662px] font-inter text-base leading-7 text-white/70 sm:text-lg">Discover handpicked hotels, resorts, and stays across your favorite destinations. Enjoy exclusive deals, fast booking, and 24/7 support.</p>
            <div class="datacore-enter datacore-enter--four mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><a href="{{ route('register') }}" class="inline-flex min-h-12 items-center justify-center rounded-[10px] bg-[#7b39fc] px-6 font-cabin text-base font-medium text-white shadow-[0_10px_24px_rgba(123,57,252,.42)] transition hover:-translate-y-0.5 hover:bg-[#8a50ff] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#c7b0ff]">Book a Free Demo</a><a href="{{ route('register') }}" class="inline-flex min-h-12 items-center justify-center rounded-[10px] bg-[#2b2344] px-6 font-cabin text-base font-medium text-[#f6f7f9] shadow-[0_10px_24px_rgba(0,0,0,.2)] transition hover:-translate-y-0.5 hover:bg-[#40345f] focus:outline-none focus-visible:ring-4 focus-visible:ring-white/60">Get Started Now</a></div>
        </section>
    </main>
</body>
</html>
